# Generated by Django 6.0.1 on 2026-01-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='body',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='body_en',
            field=models.TextField(default='', help_text='Full case study (English)', verbose_name='Body (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='body_fa',
            field=models.TextField(default='', help_text='Full case study (Farsi)', verbose_name='Body (Farsi)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('api', 'API / Backend'), ('bot', 'Automation / Bots')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(default='', help_text='Short summary for the card (English)', verbose_name='Summary (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_fa',
            field=models.TextField(default='', help_text='Short summary for the card (Farsi)', verbose_name='Summary (Farsi)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title_fa',
            field=models.CharField(default='', max_length=200, verbose_name='Title (Farsi)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin to the top of the Bento Grid'),
        ),
    ]
