services:
  db:
    image: docker.arvancloud.ir/postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: portfolio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/code
      - ./media:/code/media
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
